
services:
  app:
    build: .
    container_name: vifinancenews_app
    ports:
      - "7000:7000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./Web:/app  # Mount your entire project to /app
      - ./Web/target:/app/target  # Ensure target updates automatically

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vifinancenews_db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "ViFinanceNew#2025"
      ACCEPT_EULA: "Y"

  redis:
    image: redis
    container_name: vifinancenews_redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "AbWfAAIjcDE0ZGU2ZjBiN2ZlYTE0YzEzOTEyMWI4OWRkYjU0NDViM3AxMA"
